<a href="https://colab.research.google.com/github/ConnieC14/sent_debias/blob/master/run_pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import os

github_token = "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"
!git clone 'https://<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>:x-oauth-basic@github.com/conniec14/sent_debias.git'

fatal: destination path 'sent_debias' already exists and is not an empty directory.


In [2]:
!apt-get install git -y
%pip install torch
%pip install huggingface transformers
%pip install numpy==1.18.1
%pip install sklearn==0.20.0
%pip install matplotlib==3.1.2
# %pip install gensim==3.1.2
%pip install tqdm==4.45.0
%pip install regex==2.5.77
%pip install pattern3
%pip install boto3

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 45.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 60.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 52.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

ERROR: Could not find a version that satisfies the requirement gensim==3.1.2 (from versions: 0.2, 0.3.0, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.8.0, 3.8.1, 3.8.2, 3.8.3, 4.0.0, 4.0.1, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.3.0, 4.3.1, 4.3.2)
ERROR: No matching distribution found for gensim==3.1.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 972.4 kB/s eta 0:00:00
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.66.2
    Uninstalling tqdm-4.66.2:
      Successfully uninstalled tqdm-4.66.2
ERROR: pip's dependency resolver does not currently take into acc

In [3]:
! pip install pyflame
%load_ext pyflame
c.PyFlameMagic.flamegraph_script_path = '/content/sent_debias/debias-BERT/experiments/'

In [24]:
%config PyFlameMagic.flamegraph_script_path = '/content/sent_debias/debias-BERT/experiments/flamegraph.pl'

In [4]:
! sed -i '36s/.*/    pass/' /usr/local/lib/python3.10/dist-packages/pattern3/text/tree.py
# !unzip /content/sent_debias/debias-BERT/experiments/glue_data.zip /content/sent_debias/debias-BERT/experiments/

sed: can't read /usr/local/lib/python3.10/dist-packages/pattern3/text/tree.pyn: No such file or directory


In [5]:
task_name = "SST-2"
#"cola"
#"sst-2"
#"qnli"

glue_dir = ""
dir = "/content/sent_debias/debias-BERT/experiments"

In [40]:
%%pyflame
run = f"""python {dir}/run_classifier.py\
                    --data_dir {dir}/glue_data/{task_name} --task_name {task_name}\
                    --output_dir bert-base-uncased\
                    --debias --do_eval\
                    --do_lower_case\
                    --normalize"""

!{run}

output_dir=bert-base-uncased
03/18/2024 18:49:15 - INFO - __main__ -   device: cuda n_gpu: 1, distributed training: False, 16-bits training: False
Calling from_pretrained.
03/18/2024 18:49:15 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /root/.pytorch_pretrained_bert/distributed_-1/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
03/18/2024 18:49:15 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /root/.pytorch_pretrained_bert/distributed_-1/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmprufqf73a
03/18/2024 18:49:19 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hi

In [1]:
from sklearn.decomposition import PCA
from pca import PCA_
import unittest
import numpy as np
import numpy as np

num_components = 1

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
print(X.shape)

pca = PCA(n_components=num_components, svd_solver="auto")
y = pca.fit(X)

pca_ = PCA_(n_components=num_components)
projected_data, feat_vect = pca_.fit(X)

print(f"\nshapes: {(y.components_.shape, feat_vect.shape)}\n")

y.components_, feat_vect

(6, 2)

shapes: ((1, 2), (1, 2))



(array([[-0.83849224, -0.54491354]]), array([[-0.83849224, -0.54491354]]))

In [2]:
pca.fit_transform(X), ' ',projected_data

(array([[ 1.38340578],
        [ 2.22189802],
        [ 3.6053038 ],
        [-1.38340578],
        [-2.22189802],
        [-3.6053038 ]]),
 ' ',
 array([[ 1.38340578],
        [ 2.22189802],
        [ 3.6053038 ],
        [-1.38340578],
        [-2.22189802],
        [-3.6053038 ]]))

In [4]:
class TestPCA(unittest.TestCase):
    def test_pca(self):
        np.random.seed(0)
        num_samples = 100
        num_features = np.random.randint(10)
        X = np.random.randn(num_samples, num_features)
        
        num_components = np.random.randint(5)
        
        # Call my implementation of PCA
        pca_ = PCA_(n_components=num_components)
        _, feat_vect = pca_.fit(X)

        # Call my implementation of sklearn's pca used by method
        pca = PCA(n_components=num_components, svd_solver="auto")
        y = pca.fit(X)

        # Make sure the shapes are the same
        self.assertEqual(feat_vect.shape, y.components_.shape)

        # Make sure that the values are close to each other
        np.testing.assert_allclose(feat_vect, y.components_, atol=1e-6)

for i in range(20):
    test_suite = unittest.TestLoader().loadTestsFromTestCase(TestPCA)
    unittest.TextTestRunner().run(test_suite)

.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.
------------------